/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

import Class.Cliente;
import Class.Funciones;
import Class.Habitacion;
import Class.Reservacion;
import EDD.Arbol;
import EDD.Cola;
import EDD.HashTable;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicola
 */
public class Ventana_4 extends javax.swing.JFrame {

    public static Ventana_1 v1;
    public static Arbol<Cliente> reservaciones;
    public static Cola[] tipos_hab;
    public static HashTable<Cliente> huespedes;
    Funciones f = new Funciones();
    /**
     * Creates new form Ventana_4
     */
    public Ventana_4(Ventana_1 v1, Arbol reservaciones, HashTable huespedes, Cola[] tipos_hab) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.huespedes = huespedes;
        this.tipos_hab = tipos_hab;
        this.reservaciones = reservaciones;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        input_in_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        check_in = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        check_out = new javax.swing.JButton();
        input_out_name = new javax.swing.JTextField();
        input_out_lastname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(153, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 204, 51));
        jTabbedPane1.setFont(new java.awt.Font("Century", 2, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(158, 121, 67));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("jButton3");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        input_in_id.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        input_in_id.setForeground(new java.awt.Color(0, 0, 0));
        input_in_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_in_idActionPerformed(evt);
            }
        });
        jPanel2.add(input_in_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));

        jLabel10.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cedula:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, -1));

        jLabel11.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("REALICE SU CHECK IN");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        check_in.setBackground(new java.awt.Color(153, 0, 0));
        check_in.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        check_in.setForeground(new java.awt.Color(255, 204, 51));
        check_in.setText("Aceptar");
        check_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_inActionPerformed(evt);
            }
        });
        jPanel2.add(check_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, 50));

        jTabbedPane1.addTab("CHECK IN", jPanel2);

        jPanel1.setBackground(new java.awt.Color(158, 121, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Apellido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, -1));

        check_out.setBackground(new java.awt.Color(153, 0, 0));
        check_out.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        check_out.setForeground(new java.awt.Color(255, 204, 51));
        check_out.setText("Aceptar");
        check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_outActionPerformed(evt);
            }
        });
        jPanel1.add(check_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, 50));

        input_out_name.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        input_out_name.setForeground(new java.awt.Color(0, 0, 0));
        input_out_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_out_nameActionPerformed(evt);
            }
        });
        jPanel1.add(input_out_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, 30));

        input_out_lastname.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        input_out_lastname.setForeground(new java.awt.Color(0, 0, 0));
        input_out_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_out_lastnameActionPerformed(evt);
            }
        });
        jPanel1.add(input_out_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, 30));

        jLabel8.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("REALICE SU CHECK OUT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, -1));

        jTabbedPane1.addTab("CHECK OUT", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 480, 270));

        atras.setBackground(new java.awt.Color(153, 0, 0));
        atras.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 204, 51));
        atras.setText("ATRÁS");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IG_imagenes/sala hotel .PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_outActionPerformed
        try{
        Cliente cliente = f.EncontrarHuesped(huespedes,input_out_name.getText().toLowerCase(),input_out_lastname.getText().toLowerCase());
        Habitacion hab = cliente.getHabitacion();
        if ("simple".equals(hab.getTipo())) {
                        tipos_hab[0].encolar(hab);
                    } else if ("doble".equals(hab.getTipo())) {
                        tipos_hab[1].encolar(hab);

                    } else if ("triple".equals(hab.getTipo())) {
                        tipos_hab[2].encolar(hab);
                    } else {
                        tipos_hab[3].encolar(hab);
                    }
        hab.actualizarHistorial(cliente);
        cliente.setHabitacion(null);
        f.EliminarHuesped(huespedes, input_out_name.getText().toLowerCase(),input_out_lastname.getText().toLowerCase());
        JOptionPane.showMessageDialog(null, "El check out ha sido exitoso");
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error, por favor vuelva a intentar");
        }
    }//GEN-LAST:event_check_outActionPerformed

    private void check_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_inActionPerformed
        try{
        Cliente cliente = reservaciones.obtener(Integer.parseInt(input_in_id.getText()));
        String tipo_hab = cliente.getReservacion().getTipo_hab();
        if ("simple".equals(tipo_hab)) {
            if (!tipos_hab[0].isEmpty()) {
            cliente.setHabitacion((Habitacion)tipos_hab[0].getHead().getData());
            tipos_hab[0].Desencolar();
            reservaciones.eliminar(cliente.getId());
            huespedes.insertar(cliente.getName().toLowerCase()+cliente.getLastName().toLowerCase(), cliente);
            JOptionPane.showMessageDialog(null, "El check in ha sido exitoso");
            }else{
            JOptionPane.showMessageDialog(null, "NO hay habitaciones del tipo que desea en su reservacion disponibles");
            }
        } else if ("doble".equals(tipo_hab)) {
            if (!tipos_hab[1].isEmpty()) {
            cliente.setHabitacion((Habitacion)tipos_hab[1].getHead().getData());
            tipos_hab[1].Desencolar();
            reservaciones.eliminar(cliente.getId());
            huespedes.insertar(cliente.getName().toLowerCase()+cliente.getLastName().toLowerCase(), cliente);
            JOptionPane.showMessageDialog(null, "El check in ha sido exitoso");
            }else{
            JOptionPane.showMessageDialog(null, "NO hay habitaciones del tipo que desea en su reservacion disponibles");
            }
        } else if ("triple".equals(tipo_hab)) {
           if (!tipos_hab[2].isEmpty()) {
            cliente.setHabitacion((Habitacion)tipos_hab[2].getHead().getData());
            tipos_hab[2].Desencolar();
            reservaciones.eliminar(cliente.getId());
            huespedes.insertar(cliente.getName().toLowerCase()+cliente.getLastName().toLowerCase(), cliente);
            JOptionPane.showMessageDialog(null, "El check in ha sido exitoso");
            }else{
            JOptionPane.showMessageDialog(null, "NO hay habitaciones del tipo que desea en su reservacion disponibles");
            }

        } else if ("suite".equals(tipo_hab)) {
if (!tipos_hab[3].isEmpty()) {
            cliente.setHabitacion((Habitacion)tipos_hab[3].getHead().getData());
            tipos_hab[3].Desencolar();
            reservaciones.eliminar(cliente.getId());
            huespedes.insertar(cliente.getName().toLowerCase()+cliente.getLastName().toLowerCase(), cliente);
            JOptionPane.showMessageDialog(null, "El check in ha sido exitoso");
            }else{
            JOptionPane.showMessageDialog(null, "NO hay habitaciones del tipo que desea en su reservacion disponibles");
            }
        }
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error, por favor vuelva a intentar");

        }
    }//GEN-LAST:event_check_inActionPerformed

    private void input_in_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_in_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_in_idActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
        v1.setVisible(true);    }//GEN-LAST:event_atrasActionPerformed

    private void input_out_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_out_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_out_nameActionPerformed

    private void input_out_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_out_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_out_lastnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_4(v1, reservaciones, huespedes, tipos_hab).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton check_in;
    private javax.swing.JButton check_out;
    private javax.swing.JTextField input_in_id;
    private javax.swing.JTextField input_out_lastname;
    private javax.swing.JTextField input_out_name;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
