/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

/**
 *
 * @author Nicola
 */
public class Ventana_3 extends javax.swing.JFrame {

    /**
     * Creates new form Vetana_3
     */
    public Ventana_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num_hab = new javax.swing.JTextField();
        buscar_hab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historial_habitacion = new javax.swing.JTextArea();
        atras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num_hab.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        num_hab.setForeground(new java.awt.Color(0, 0, 0));
        num_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_habActionPerformed(evt);
            }
        });
        jPanel1.add(num_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 30));

        buscar_hab.setBackground(new java.awt.Color(153, 0, 0));
        buscar_hab.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        buscar_hab.setForeground(new java.awt.Color(255, 204, 51));
        buscar_hab.setText("BUSCAR");
        buscar_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_habActionPerformed(evt);
            }
        });
        jPanel1.add(buscar_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 160, 50));

        Historial_habitacion.setEditable(false);
        Historial_habitacion.setBackground(new java.awt.Color(158, 121, 67));
        Historial_habitacion.setColumns(20);
        Historial_habitacion.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        Historial_habitacion.setForeground(new java.awt.Color(0, 0, 0));
        Historial_habitacion.setRows(5);
        jScrollPane1.setViewportView(Historial_habitacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 550, 220));

        atras.setBackground(new java.awt.Color(153, 0, 0));
        atras.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 204, 51));
        atras.setText("ATRÁS");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));

        jLabel3.setBackground(new java.awt.Color(153, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NUMERO DE HABITACION: ");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IG_imagenes/habitación hotel.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_habActionPerformed

    private void buscar_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar_habActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Historial_habitacion;
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar_hab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField num_hab;
    // End of variables declaration//GEN-END:variables
}
