/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

import Class.Cliente;
import Class.Funciones;
import EDD.Arbol;
import EDD.Cola;
import EDD.HashTable;

/**
 *
 * @author Nicola
 */
public class Ventana_1 extends javax.swing.JFrame {

    public static Cola[] tipos_hab;
    public static HashTable<Cliente> huespedes;
    public static Arbol reservaciones;

    Funciones f = new Funciones();

    /**
     * Creates new form Vetana_1
     */
    public Ventana_1(Cola[] tipos_hab, HashTable huespedes, Arbol reservaciones) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.huespedes = huespedes;
        this.tipos_hab=tipos_hab;
        this.reservaciones=reservaciones;
    }

    public static HashTable getHashTable() {
        return huespedes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registro_clientes = new javax.swing.JButton();
        bus_reservacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        check = new javax.swing.JButton();
        historial_hab = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 115, -1, -1));

        registro_clientes.setBackground(new java.awt.Color(153, 0, 0));
        registro_clientes.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        registro_clientes.setForeground(new java.awt.Color(255, 204, 51));
        registro_clientes.setText("REGISTRO DE CLIENTES");
        registro_clientes.setMaximumSize(new java.awt.Dimension(305, 29));
        registro_clientes.setMinimumSize(new java.awt.Dimension(305, 29));
        registro_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(registro_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 350, 60));

        bus_reservacion.setBackground(new java.awt.Color(153, 0, 0));
        bus_reservacion.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        bus_reservacion.setForeground(new java.awt.Color(255, 204, 51));
        bus_reservacion.setText("BUSQUEDA DE RESERVACION");
        bus_reservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bus_reservacionActionPerformed(evt);
            }
        });
        getContentPane().add(bus_reservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 350, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IG_imagenes/bienvenido-de-nuevo-3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        check.setBackground(new java.awt.Color(153, 0, 0));
        check.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        check.setForeground(new java.awt.Color(255, 204, 51));
        check.setText("CHECK IN / CHECK OUT");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        getContentPane().add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 350, 60));

        historial_hab.setBackground(new java.awt.Color(153, 0, 0));
        historial_hab.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        historial_hab.setForeground(new java.awt.Color(255, 204, 51));
        historial_hab.setText("HISTORIAL DE HABITACION");
        historial_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_habActionPerformed(evt);
            }
        });
        getContentPane().add(historial_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IG_imagenes/entrada hotel.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bus_reservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bus_reservacionActionPerformed
        this.setVisible(false);
        Ventana_2 v2 = new Ventana_2(this, reservaciones);
        v2.setVisible(true);    }//GEN-LAST:event_bus_reservacionActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
this.setVisible(false);
        Ventana_4 v4 = new Ventana_4(this, reservaciones,  huespedes,  tipos_hab);
        v4.setVisible(true);    }//GEN-LAST:event_checkActionPerformed

    private void historial_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historial_habActionPerformed

    private void registro_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_clientesActionPerformed
        this.setVisible(false);
        Ventana_5 v5 = new Ventana_5(this, huespedes);
        v5.setVisible(true);
    }//GEN-LAST:event_registro_clientesActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_1.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_1(tipos_hab, huespedes,reservaciones).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bus_reservacion;
    private javax.swing.JButton check;
    private javax.swing.JButton historial_hab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registro_clientes;
    // End of variables declaration//GEN-END:variables

    void setHashTable(HashTable<Cliente> huespedes) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
