/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IG;

/**
 *
 * @author Nicola
 */
public class Vetana_1 extends javax.swing.JFrame {

    /**
     * Creates new form Vetana_1
     */
    public Vetana_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registro_clientes = new javax.swing.JButton();
        historial_hab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        historial_hab1 = new javax.swing.JButton();
        historial_hab2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 500));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 115, -1, -1));

        registro_clientes.setBackground(new java.awt.Color(153, 0, 0));
        registro_clientes.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        registro_clientes.setForeground(new java.awt.Color(255, 204, 51));
        registro_clientes.setText("REGISTRO DE CLIENTES");
        registro_clientes.setMaximumSize(new java.awt.Dimension(305, 29));
        registro_clientes.setMinimumSize(new java.awt.Dimension(305, 29));
        getContentPane().add(registro_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 350, 60));

        historial_hab.setBackground(new java.awt.Color(153, 0, 0));
        historial_hab.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        historial_hab.setForeground(new java.awt.Color(255, 204, 51));
        historial_hab.setText("BUSQUEDA DE RESERVACION");
        historial_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_habActionPerformed(evt);
            }
        });
        getContentPane().add(historial_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 350, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IG_imagenes/bienvenido-de-nuevo-3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        historial_hab1.setBackground(new java.awt.Color(153, 0, 0));
        historial_hab1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        historial_hab1.setForeground(new java.awt.Color(255, 204, 51));
        historial_hab1.setText("CHECK IN / CHECK OUT");
        historial_hab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_hab1ActionPerformed(evt);
            }
        });
        getContentPane().add(historial_hab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 350, 60));

        historial_hab2.setBackground(new java.awt.Color(153, 0, 0));
        historial_hab2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        historial_hab2.setForeground(new java.awt.Color(255, 204, 51));
        historial_hab2.setText("HISTORIAL DE HABITACION");
        historial_hab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_hab2ActionPerformed(evt);
            }
        });
        getContentPane().add(historial_hab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IG_imagenes/entrada hotel.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historial_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historial_habActionPerformed

    private void historial_hab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_hab1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historial_hab1ActionPerformed

    private void historial_hab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_hab2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historial_hab2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vetana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vetana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vetana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vetana_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vetana_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton historial_hab;
    private javax.swing.JButton historial_hab1;
    private javax.swing.JButton historial_hab2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registro_clientes;
    // End of variables declaration//GEN-END:variables
}
